const sections=document.querySelectorAll('.page-section');const nav=document.querySelectorAll('.nav-item');const title=document.getElementById('pageTitle');
const titles={dashboard:'Good morning, Vrinda ✦',expenses:'Expenses',budgets:'Budgets',splits:'Split Bills',lending:'Lending & Borrowing',statements:'Bank Statements',parent:'Parent Control',settings:'Settings'};
function showSection(id){sections.forEach(s=>s.classList.toggle('active-section',s.id===id));nav.forEach(n=>n.classList.toggle('active',n.dataset.section===id));title.innerHTML=titles[id]||'Spendly';document.querySelector('.sidebar')?.classList.remove('open');window.scrollTo({top:0,behavior:'smooth'});}
nav.forEach(n=>n.addEventListener('click',()=>showSection(n.dataset.section)));document.querySelectorAll('[data-section-jump]').forEach(b=>b.addEventListener('click',()=>showSection(b.dataset.sectionJump)));
document.getElementById('menuBtn').addEventListener('click',()=>document.querySelector('.sidebar').classList.toggle('open'));
const bars=document.getElementById('bars');[32,48,40,65,54,72,60,85,49,66,74,58,91,62,78,53,70,82,46,61,88,69,57,73].forEach(h=>{const b=document.createElement('span');b.className='bar';b.style.height=h+'%';bars.appendChild(b)});
const modal=document.getElementById('expenseModal');document.querySelectorAll('[data-open-modal]').forEach(b=>b.addEventListener('click',()=>modal.classList.add('show')));document.querySelectorAll('[data-close-modal]').forEach(b=>b.addEventListener('click',()=>modal.classList.remove('show')));modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('show')});
let demoExpenses=[['Swiggy','Food & Dining','Today','₹420'],['Uber','Travel','Today','₹280'],['Amazon','Shopping','Yesterday','₹1,850'],['Electricity Bill','Bills','Sep 22','₹1,240'],['Netflix','Entertainment','Sep 21','₹649']];
function renderRows(list=demoExpenses){const box=document.getElementById('expenseRows');box.innerHTML=list.map(x=>`<div class="table-row"><span><b>${x[0]}</b><small>Manual transaction</small></span><span>${x[1]}</span><span>${x[2]}</span><span class="negative">− ${x[3]}</span></div>`).join('')};renderRows();
document.getElementById('expenseSearch').addEventListener('input',e=>{const q=e.target.value.toLowerCase();renderRows(demoExpenses.filter(x=>x.join(' ').toLowerCase().includes(q))) });
document.getElementById('addExpense').addEventListener('click',()=>{const merchant=document.getElementById('merchant').value.trim()||'New expense';const amount=Number(document.getElementById('amount').value)||0;const category=document.getElementById('category').value;demoExpenses.unshift([merchant,category,'Just now','₹'+amount.toLocaleString('en-IN')]);renderRows();modal.classList.remove('show');document.getElementById('merchant').value='';document.getElementById('amount').value='';showSection('expenses')});
document.getElementById('fakeUpload').addEventListener('click',()=>{document.getElementById('uploadStatus').textContent='Demo upload selected — connect your Java backend here later.'});
